# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Geminica
subtitle: Sketch artist and software engineer in Humboldt County, California
email: geminica@gmail.com
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: false
breadcrumbs: false
breadcrumb_home_label : "geminica"
breadcrumb_separator : "->"
assets: /assets

defaults:
  # _posts
  - scope:
      path: "journal"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      paginate: 5
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      author_profile: false
      layout: single
      read_time: false
      comments: false
      share: false
      related: false
  # sketches
  - scope:
      path: "/sketches"
      type: gallery
    values:
      author_profile: false
      layout: single
      read_time: false
      comments: false
      share: false
      related: false
timezone: America/Los_Angeles
# Site Author
author:
  name             : "Kalina Geminica Wilson"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Sketcher, software developer, sci fi fan, traveler"
  location         : "Eureka, California"
  email            : geminica @ gmail . com
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kgeminica"

include:
 - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/kgeminica"
      
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache